# Generated by Django 4.2.2 on 2023-07-04 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(blank=True, db_column='is_delete', default=False, null=True, verbose_name='是否删除')),
                ('createTime', models.DateTimeField(auto_now_add=True, db_column='create_time', null=True, verbose_name='创建时间')),
                ('updataTime', models.DateTimeField(auto_now=True, db_column='updata_time', null=True, verbose_name='修改时间')),
                ('title', models.CharField(max_length=32, verbose_name='通知标题')),
                ('detail', models.TextField(default='', null=True, verbose_name='通知详情')),
            ],
            options={
                'verbose_name': '通知',
                'db_table': 'notices',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(blank=True, db_column='is_delete', default=False, null=True, verbose_name='是否删除')),
                ('createTime', models.DateTimeField(auto_now_add=True, db_column='create_time', null=True, verbose_name='创建时间')),
                ('updataTime', models.DateTimeField(auto_now=True, db_column='updata_time', null=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=32, verbose_name='角色名称')),
                ('detail', models.TextField(default='', null=True, verbose_name='角色说明')),
                ('permission', models.TextField(verbose_name='选中的权限')),
                ('pathList', models.TextField(db_column='path_list', verbose_name='关于权限的所有路由')),
            ],
            options={
                'verbose_name': '用户角色',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(blank=True, db_column='is_delete', default=False, null=True, verbose_name='是否删除')),
                ('createTime', models.DateTimeField(auto_now_add=True, db_column='create_time', null=True, verbose_name='创建时间')),
                ('updataTime', models.DateTimeField(auto_now=True, db_column='updata_time', null=True, verbose_name='修改时间')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号&账号')),
                ('passWord', models.CharField(db_column='pass_word', max_length=64, verbose_name='密码')),
                ('passWordMd5', models.CharField(db_column='pass_word_md5', max_length=64, verbose_name='加密密码')),
                ('name', models.CharField(default='', max_length=32, verbose_name='姓名')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别')),
                ('age', models.IntegerField(null=True, verbose_name='年龄')),
                ('region', models.CharField(default='', max_length=64, verbose_name='省市区')),
                ('address', models.CharField(default='', max_length=64, verbose_name='详细地址')),
                ('type', models.IntegerField(choices=[(1, '内置'), (2, '创建')], default=2, verbose_name='用户类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('detail', models.TextField(default='', null=True, verbose_name='账号说明')),
                ('roleId', models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.roles', verbose_name='用户角色')),
            ],
            options={
                'verbose_name': '用户',
                'db_table': 'users',
            },
        ),
    ]
